---
title: "DATA 606 Data Project Proposal"
author: "Yuen Chun Wong"
output: pdf_document
---



### Data Preparation


```{r load-and-prepare-data}
#All collision by date
#CollisionByDate <- tbl_df(read.csv("109PoliceMotorCollision.csv", stringsAsFactors = FALSE, check.names = FALSE))

#Weather By Date
#WeatherByDate <- tbl_df(read.csv("109PoliceMotorCollision.csv", stringsAsFactors = FALSE, check.names = FALSE))

#get subset, weather = rainy
#bad_date_Collision <- subset(CollisionByDate, PRCP > 0 || snow > 0 .... )


#NOAA weather data
#SNOW - Snowfall
#PRCP - Precipitation

```


### Research question 

Does car accident is predictable by weather conditions?

109 Precinct in Flushing, NY (https://goo.gl/maps/9aPSt9yqDp42), from one of my previous project I found that  has most of the car accidents in entire New York City (http://rpubs.com/nyjon2k/316465/) #3 "NYPD Motor Vehicle Collisions" section.  Therefore, I am interested: Does the weather condition lead to more car accidents?  For example, there will be more vehicle collosion in rainy day while there will be more pedestrian and cyclists killed.

Research question:
By weather condition (such as rain or snow ), What will be car accident frequency be in 109 Police station?

Does the average of car accident are same between good weather and bad weather?

Any correlation between # of car accident and weather condition?

Can we predict how many car accident with given weather condition?

### Cases 

**What are the cases, and how many are there?**

Each case represent the sum of the car accidents in a weather conditions. 3 years daily data will be collected in observations in the given data set.


### Data collection 



1) NYPD Moter Vehicle Collison Data is maintained by NYPD department
(https://catalog.data.gov/dataset/nypd-motor-vehicle-collisions-07420)

2) National Ocean and Atmosperic Adiminstration (NOAA) Historical data.
(https://www.climate.gov/maps-data/dataset/past-weather-zip-code-data-table)



### Type of study 

This is an observational study.


### Data Source 

I am going to download 2 dataset and merge them together by date before analysis.

Both data set are daily data.

NYPD Moter Vehicle Collision Data can be queried with URL/JSON request:
(https://data.cityofnewyork.us/Public-Safety/NYPD-Motor-Vehicle-Collisions/h9gi-nx95/data)
or it can be downloaded from Google Cloud (https://cloud.google.com/bigquery/public-data/)

NOAA historical weather data: 
weather data of area near 109 police station. (https://www.climate.gov/maps-data/dataset/past-weather-zip-code-data-table).  Data can be collected with zip code or country information.
-Click the link above, then click "Data Access" and choose "CDO Search"
-In the Climate Data Online Search page
 -Choose "Daily Summaries", Choose "Date Range", Choose "Counties" for station
 -Enter "Queens, New York" and then click search
 -Filter data by weather station "USW00094789" or 	"JFK INTERNATIONAL AIRPORT, NY US"
 -Once in the result page, click "Add to cart" in Queens County, NY section
 -Click View Cart, Choose "Custom GHCN-Daily CSV" for output format
 -Once again confirm date range, click "continue"
 -In custom output format, click "Select All" and "continue"
 -enter email address and confirm the subscription, the data file will be sent to the email address.

Data defination could be found:

https://catalog.data.gov/harvest/object/c3268bdd-a141-4ab6-808d-e0d1f23b7201

https://www.ncdc.noaa.gov/cdo-web/datasets#GHCND



### Response 

**What is the response variable, and what type is it (numerical/categorical)?**

The response variable is car accident frequency per day and is numerical.


### Explanatory 

**What is the explanatory variable, and what type is it (numerical/categorival)?**

The explanatory variable is weather condition and is categorival.


### Relevant summary statistics 

**Provide summary statistics relevant to your research question. For example, if you are comparing means across groups provide means, SDs, sample sizes of each group. This step requires the use of R, hence a code chunk is provided below. Insert more code chunks as needed.**

I plan to include histogram of the accident in general from 2013 to 2017

I also want to do the # of accident per day and correlation with weather condition (such as amont of rain or snow)

At the end, i will do linear regression for the # of accident with weather condition


